name: CI workflow for Blog

on:
    push:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-22.04

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # Fetch all history for all branches and tags
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20.17.0'

            - name: Install dependencies
              run: npm install

            - name: Run lint
              run: npm run lint

            - name: Run format check
              run: npm run format

            - name: Check commit messages
              uses: wagoid/commitlint-github-action@v6
              with:
                  configFile: commitlint.config.cjs
